AWSTemplateFormatVersion: 2010-09-09
  
Resources:

  AmplifyRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
        - Effect: 'Allow'
          Principal: 
            Service: 
              - 'amplify.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess-Amplify'
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      RoleName: AmplifyRole

  Amplify:
    Type: "AWS::Amplify::App"
    Properties:
      Name: "team-3-otterview-frontend"
      Repository: "https://github.com/swen-514-614-spr-2023-2/team-3"
      AccessToken: "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"
      EnvironmentVariables:
        - Name: "AMPLIFY_MONOREPO_APP_ROOT"
          Value: "otterview-frontend"
        - Name: "AMPLIFY_DIFF_DEPLOY"
          Value: false
        - Name: "_LIVE_UPDATES"
          Value: '[{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]'
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      BuildSpec: |-
        "version: 1
        applications:
          - appRoot: team-3-otterview-frontend
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: build
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*"

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt Amplify.AppId
      BranchName: main
      EnableAutoBuild: true
      Stage: PRODUCTION

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: "otterview.com"
      AppId: !GetAtt Amplify.AppId
      SubDomainSettings:
        - Prefix: main
          BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  AmplifyAppId:
    Value: !Ref Amplify

  DefaultDomain:
    Value: !Sub main.${Amplify.DefaultDomain}

  BranchUrl:
    Value: !Sub ${AmplifyBranch.BranchName}.${AmplifyDomain.DomainName}