#IN PROGRESS

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
        - Effect: 'Allow'
          Principal: 
            Service: 
              - 'amplify.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess-Amplify'
      RoleName: AmplifyRole

  Amplify:
    Type: AWS::Amplify::App
    DeletionPolicy: Delete
    Properties:
      Repository: "https://github.com/swen-514-614-spr-2023-2/team-3"
      Name: "team-3-otterview-frontend"
      EnvironmentVariables:
        - Name: "AMPLIFY_MONOREPO_APP_ROOT"
          Value: "otterview-frontend"
        - Name: "AMPLIFY_DIFF_DEPLOY"
          Value: false
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      AccessToken: "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"
      AutoBranchCreationConfig:
        EnableAutoBuild: True
        BuildSpec:
          "version: 1
          applications:
            - frontend:
                phases:
                  preBuild:
                    commands:
                      - npm ci
                  build:
                    commands:
                      - npm run build
                artifacts:
                  baseDirectory: build
                  files:
                    - '**/*'
                cache:
                  paths:
                    - node_modules/**/*
              appRoot: otterview-frontend"

      