Resources:
    Function:
        Type: AWS::Lambda::Function
        Properties: 
          Code:
            ZipFile: |
                import boto3
        
                client = boto3.client('comprehend')
                
                def lambda_handler(event, context):
                    result = {
                        "Sentiment": client.detect_sentiment(Text = event['inputTranscript'], LanguageCode='en')['Sentiment'],
                        "SentimentScore": client.detect_sentiment(Text = event['inputTranscript'], LanguageCode='en')['SentimentScore']
                    }
                    return result