AWSTemplateFormatVersion: 2010-09-09

Resources:
  SentimentFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
        - Effect: 'Allow'
          Principal: 
            Service: 
              - 'lambda.amazonaws.com'
              - 'comprehend.amazonaws.com'
              - 'apigateway.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ComprehendFullAccess'
        - 'arn:aws:iam::aws:policy/service-role/ComprehendDataAccessRolePolicy'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      RoleName: LambdaRole

  SentimentFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code:
        ZipFile: |
          import boto3
  
          client = boto3.client('comprehend')
          
          def lambda_handler(event, context):
            result = {
              'Sentiment': client.detect_sentiment(Text = event['inputTranscript'], LanguageCode='en')['Sentiment'],
              'SentimentScore': client.detect_sentiment(Text = event['inputTranscript'], LanguageCode='en')['SentimentScore']
            }
            return result
      FunctionName: 'SentimentFunction'
      Handler: index.lambda_handler
      Role: !GetAtt SentimentFunctionRole.Arn
      Runtime: 'python3.9'