tests:
  image: node:latest
  stage: test
  before_script:
    - node --version
    - npm install
    - npm install -g jest
    - npm install jest-environment-jsdom
  script:
    - npx jest --ci --config jest.config.js