image:
  name: andymeneely/swen331fuzzer # don't change this

  entrypoint: [""]  # don't change this

before_script:
  # don't change these either

  - chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
  - echo '[+] Starting mysql...'
  - service mysql start
  - echo '[+] Starting apache'
  - service apache2 start
fuzzrunner:
  script:
    # here is where you can write your commands to run your fuzzer or any custom setup commands
    - pip install mechanicalsoup
    - pip install argparse

    - echo "hello class"
    # need some example files for vectors and words? These are on the image

    - cat /words.txt
    - cat /vectors.txt
    - cat /badchars.txt
    # An example fuzzer command. Note the url is DIFFERENT than XAMPP example (no /dvwa).

    - python fuzz.py test http://127.0.0.1/ --custom-auth=dvwa --common-words=commonWords.txt --extensions=extensions.txt --vectors=vectors.txt --sanitized-chars=sanitizedChars.txt --sensitive=sensitive.txt --slow=500
    
  stage: test